# BrainCraft.io DevContainer mise configuration
# This file configures mise to automatically trust the /workspace directory

[settings]
# Automatically trust configuration files in /workspace
trusted_config_paths = ["/workspace"]

# Enable experimental features for better DevContainer experience
experimental = true

# Yes mode - assume yes for all prompts (useful for automation)
yes = true

# Suppress warnings for missing tools in DevContainer
status.missing_tools = "never"

# Don't be paranoid about security checks (we trust our DevContainer)
paranoid = false

# Keep output visible for debugging
quiet = false
verbose = false

# Auto-install missing tools when commands are run
not_found_auto_install = true

# Number of parallel jobs for installations
jobs = 4

# Essential tools that should be pre-installed in devcontainer
# These are the minimum required for immediate productivity
# Full tool list is in /workspace/.config/mise/conf.d/00-tools.toml
[tools]
# Core languages - match versions from workspace config
node = "24"       # Latest LTS - essential for npm packages
python = "3.13.5" # Latest stable - essential for Python tools
go = "1.24.5"     # Specific version for consistency

# Critical package managers
pnpm = "latest"   # Faster npm alternative
pipx = "latest"   # Python app isolation

# Essential dev tools
gh = "latest"     # GitHub CLI - needed for auth
jq = "latest"     # JSON processor - used by many scripts
