name: Build and Publish DevContainer Image

on:
  push:
    branches: [main]
    paths:
      - "devcontainer/**"
      - ".github/workflows/image-build.yaml"
      - ".mise.toml"
  pull_request:
    paths:
      - "devcontainer/**"
      - ".github/workflows/image-build.yaml"
  workflow_dispatch:
    inputs:
      push:
        description: "Push image to registry"
        required: false
        type: boolean
        default: true
  schedule:
    - cron: "0 0 * * 1" # Weekly rebuilds for security updates

permissions:
  contents: read
  packages: write
  id-token: write # For OIDC signing

jobs:
  build:
    uses: braincraftio/actions/.github/workflows/container-build.yml@main
    with:
      image-name: ghcr.io/braincraftio/containers
      context: ./devcontainer
      dockerfile: ./devcontainer/Dockerfile
      platforms: linux/amd64,linux/arm64
      push: ${{ github.event_name != 'pull_request' }}
      calling-repository: ${{ github.repository }}
      tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=raw,value=devcontainer-latest,enable={{is_default_branch}}
        type=sha,prefix=devcontainer-
    secrets: inherit